# Generated by Django 4.2.1 on 2023-06-27 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmedicalrecord',
            name='doctor',
        ),
    ]
