# Generated by Django 4.2.1 on 2023-05-28 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_remove_patient_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicalrecord',
            name='date',
            field=models.DateField(),
        ),
    ]
